version: '3.4'

services:
  checkoutdb:
    container_name: checkoutdb
    environment:
        SA_PASSWORD: "Test@2022"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  checkout.api:
      container_name: checkoutapi
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:OrderingConnectionString=Server=checkoutdb;Database=OrderDb;User Id=sa;Password=Test@2022"
      depends_on:
        - checkoutdb
      ports:
        - "5000:80"      